const KEY='nicksLifeDashboard.v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const iso=()=>new Date().toISOString().slice(0,10);
const clone=x=>JSON.parse(JSON.stringify(x));
const seed={settings:{goal:20},today:[
{id:uid(),title:'Get log splitter into backyard',lane:'Must',category:'Property',base:8,pita:false,done:false},
{id:uid(),title:'Clean kitchen + sink area',lane:'Should',category:'House',base:5,pita:false,done:false},
{id:uid(),title:'Split firewood',lane:'Should',category:'Property',base:10,pita:false,done:false},
{id:uid(),title:'30 minutes on Mr. Darkness / music',lane:'Want',category:'Me',base:5,pita:false,done:false}],
backlog:[{id:uid(),title:'Mount projector on wall',lane:'Should',category:'House',base:5,pita:false,notes:''},{id:uid(),title:'Turn downstairs bedroom into drying room',lane:'Should',category:'House',base:8,pita:false,notes:'After outdoor harvest'},{id:uid(),title:'Plan winter generator setup',lane:'Bonus',category:'Planning',base:3,pita:false,notes:'Fridge + lights + internet'}],
inbox:[],projects:[
['Firewood + winter prep','Home + Property','Active','Get splitter into backyard; split and stack firewood','High',15],
['Mr. Darkness EP','Creative','Active','Finish EP track sequence, art, and release setup','High',55],
['Cheese Louise launch','Podcast','Active','Build episode pipeline and launch checklist','High',30],
['Homestead landscape plan','Garden + Homestead','Active','Finalize terraces, water movement, orchard, wildlife areas','Medium',35],
['2027 garden plan','Garden + Homestead','Planning','Build seed-start calendar and greenhouse plan','Medium',20],
['Garage apartment plan','Home + Property','Someday','Finalize layout and budget before next design pass','Low',25],
['Modern Tiki album','Creative','Next','Assemble album and release plan','Medium',25],
['Fall Review rollout','Work','Active','Finalize walk sheet and sales handoff process','High',60]
].map(p=>({id:uid(),title:p[0],area:p[1],status:p[2],next:p[3],priority:p[4],progress:p[5],notes:''})),
routines:[['Choose 1 Must + 2 Should + 1 Want','Daily','Morning','Personal',1],['Log points + reset Today','Daily','Evening','Personal',1],['Review Inbox / Backlog / Projects','Weekly','Weekend','Personal',3],['Creative block','Weekly','Any day','Creative',5],['Admin sweep','Monthly','First weekend','Admin',3]].map(r=>({id:uid(),done:false,title:r[0],frequency:r[1],when:r[2],area:r[3],base:r[4]})),
admin:[],rewards:[{cost:10,title:'30 min guilt-free hobby time',meaning:'Music, garden, podcast, whatever you want'},{cost:20,title:'Full hour hobby time',meaning:'No chores sneaking into it'},{cost:30,title:'Do-absolutely-nothing block',meaning:'Movie, gaming, podcast, couch'},{cost:50,title:'Small treat / purchase',meaning:'Something fun'},{cost:100,title:'Bigger project reward',meaning:'Project purchase or half-day off'}],claims:[],history:[]};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?Object.assign(clone(seed),x,{settings:Object.assign({},seed.settings,x.settings||{})}):clone(seed)}catch(e){return clone(seed)}}
let state=load(),more='backlog';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pts=()=>state.today.reduce((n,t)=>n+(t.done?(+t.base||0)+(t.pita?2:0):0),0);
const spent=()=>state.claims.reduce((n,c)=>n+(+c.cost||0),0);
const logged=()=>state.history.reduce((n,h)=>n+(+h.points||0),0);
const bank=()=>logged()+pts()-spent();
function streak(){let a=[...state.history].sort((a,b)=>a.date.localeCompare(b.date)),n=0;for(let i=a.length-1;i>=0;i--){if(a[i].hit)n++;else break}return n}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function header(){const p=pts(),g=+state.settings.goal||20;$('#dateLine').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric'}).format(new Date())+' • 1 Must + 2 Should + 1 Want';$('#pointsToday').textContent=p;$('#goalValue').textContent=g;$('#goalBar').style.width=Math.min(100,p/g*100)+'%';$('#streakValue').textContent=streak();$('#bankValue').textContent=bank()}
function taskHTML(t){return `<div class="task ${t.done?'done':''}"><input class="check" type="checkbox" ${t.done?'checked':''} data-check-task="${t.id}"><div><div class="task-title">${esc(t.title)}</div><div class="meta"><span class="tag">${esc(t.lane)}</span><span class="tag">${esc(t.category)}</span>${t.pita?'<span class="tag">PITA +2</span>':''}</div><div class="row-actions"><button class="ghost" data-pita="${t.id}">${t.pita?'Remove +2':'PITA +2'}</button><button class="ghost" data-edit-task="${t.id}">Edit</button><button class="ghost" data-backlog-task="${t.id}">Backlog</button></div></div><div class="pts">${(+t.base||0)+(t.done&&t.pita?2:0)} pts</div></div>`}
function renderToday(){$('#todayList').innerHTML=state.today.length?state.today.map(taskHTML).join(''):'<div class="empty">Today is empty. Add only what matters.</div>'}
function renderInbox(){$('#inboxList').innerHTML=state.inbox.length?state.inbox.map(i=>`<div class="card"><div class="inbox-row"><div><h3>${esc(i.title)}</h3><div class="small">${esc(i.area||'Unsorted')}</div></div><button class="pill" data-process-inbox="${i.id}">Process</button></div></div>`).join(''):'<div class="empty">Inbox empty.</div>'}
function renderProjects(){const q=($('#projectSearch').value||'').toLowerCase();const rows=state.projects.filter(p=>(p.title+' '+p.area+' '+p.status+' '+p.next).toLowerCase().includes(q));$('#projectList').innerHTML=rows.map(p=>`<div class="card"><div class="project-top"><div><h3>${esc(p.title)}</h3><div class="small">${esc(p.area)} • ${esc(p.priority)} priority</div></div><span class="status">${esc(p.status)}</span></div><div class="small" style="margin-top:8px"><b>Next:</b> ${esc(p.next)}</div><div class="project-progress"><input type="range" min="0" max="100" value="${p.progress}" data-project-progress="${p.id}"><span>${p.progress}%</span></div><div class="row-actions"><button class="ghost" data-project-today="${p.id}">Next → Today</button><button class="ghost" data-edit-project="${p.id}">Edit</button></div></div>`).join('')||'<div class="empty">No matching projects.</div>'}
function backlogHTML(){return `<div class="section-head"><div class="small">Everything can live here without yelling at you.</div><button class="pill" data-add="backlog">+ Task</button></div>${state.backlog.map(t=>`<div class="card"><h3>${esc(t.title)}</h3><div class="small">${esc(t.category)} • ${t.base} pts • ${esc(t.lane)}</div><div class="row-actions"><button class="ghost" data-promote="${t.id}">Move to Today</button><button class="ghost danger" data-delete-backlog="${t.id}">Delete</button></div></div>`).join('')||'<div class="empty">Backlog empty.</div>'}`}
function routinesHTML(){return state.routines.map(r=>`<div class="task ${r.done?'done':''}"><input class="check" type="checkbox" ${r.done?'checked':''} data-check-routine="${r.id}"><div><div class="task-title">${esc(r.title)}</div><div class="small">${esc(r.frequency)} • ${esc(r.when)} • ${esc(r.area)}</div><div class="row-actions"><button class="ghost" data-routine-today="${r.id}">Add to Today</button></div></div><div class="pts">${r.base} pts</div></div>`).join('')}
function adminHTML(){return `<div class="section-head"><div class="small">Returns, warranties, subscriptions, appointments, paperwork.</div><button class="pill" data-add="admin">+ Admin</button></div>${state.admin.map(a=>`<div class="task ${a.done?'done':''}"><input class="check" type="checkbox" ${a.done?'checked':''} data-check-admin="${a.id}"><div><div class="task-title">${esc(a.title)}</div><div class="small">${esc(a.type||'Admin')} • ${esc(a.status||'Open')} ${a.due?'• '+esc(a.due):''}</div></div></div>`).join('')||'<div class="empty">No admin predators currently visible.</div>'}`}
function rewardsHTML(){return `<div class="note">Base points: 1 tiny • 3 quick • 5 medium • 8 substantial • 10 big • +2 PITA.</div>${state.rewards.map(r=>`<div class="card reward"><div><h3>${esc(r.title)}</h3><div class="small">${esc(r.meaning)}</div></div><button data-claim="${r.cost}" data-title="${esc(r.title)}" ${bank()<r.cost?'disabled':''}>${r.cost} pts</button></div>`).join('')}`}
function statsHTML(){return `<div class="cards"><div class="metric"><strong>${streak()}</strong><span>Streak</span></div><div class="metric"><strong>${state.history.filter(h=>h.hit).length}</strong><span>Goals Hit</span></div><div class="metric"><strong>${logged()}</strong><span>Logged Pts</span></div><div class="metric"><strong>${bank()}</strong><span>Bank</span></div></div><div class="toolbar"><button id="goalBtn">Change Goal</button><button id="exportBtn">Export Backup</button></div>${state.history.slice().reverse().map(h=>`<div class="card"><b>${h.date}</b><div class="small">${h.points} points • goal ${h.goal}</div></div>`).join('')||'<div class="empty">Close your first day to start history.</div>'}`}
function renderMore(){$$('[data-more]').forEach(b=>b.classList.toggle('strong',b.dataset.more===more));$('#moreContent').innerHTML=more==='backlog'?backlogHTML():more==='routines'?routinesHTML():more==='admin'?adminHTML():more==='rewards'?rewardsHTML():statsHTML()}
function render(){header();renderToday();renderInbox();renderProjects();renderMore()}
function nav(name){$$('.section').forEach(s=>s.classList.toggle('active',s.id===name));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$('#fab').style.display=name==='today'?'block':'none';scrollTo({top:0,behavior:'smooth'})}
function actions(){return '<div class="sheet-actions"><button class="secondary" data-close-modal>Cancel</button><button class="primary" id="saveModal">Save</button></div>'}
function modal(type,obj={}){const m=$('#modal');m.dataset.type=type;m.dataset.id=obj.id||'';$('#modalTitle').textContent=obj.id?'Edit':'Add';let b='';if(type==='task'||type==='backlog')b=`<div class="form-grid"><div class="field full"><label>Task</label><input id="fTitle" value="${esc(obj.title||'')}"></div><div class="field"><label>Lane</label><select id="fLane">${['Must','Should','Want','Bonus'].map(x=>`<option ${obj.lane===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Category</label><input id="fCategory" value="${esc(obj.category||'Personal')}"></div><div class="field"><label>Base points</label><select id="fBase">${[1,3,5,8,10].map(x=>`<option ${+obj.base===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>PITA +2</label><select id="fPita"><option value="false">No</option><option value="true" ${obj.pita?'selected':''}>Yes</option></select></div></div>${actions()}`;
if(type==='inbox')b=`<div class="form-grid"><div class="field full"><label>Thing</label><input id="fTitle"></div><div class="field"><label>Area</label><input id="fArea"></div><div class="field full"><label>Notes</label><textarea id="fNotes"></textarea></div></div>${actions()}`;
if(type==='project')b=`<div class="form-grid"><div class="field full"><label>Project</label><input id="fTitle" value="${esc(obj.title||'')}"></div><div class="field"><label>Area</label><input id="fArea" value="${esc(obj.area||'')}"></div><div class="field"><label>Status</label><select id="fStatus">${['Active','Next','Planning','Someday','Done'].map(x=>`<option ${obj.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select id="fPriority">${['High','Medium','Low'].map(x=>`<option ${obj.priority===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>Next action</label><input id="fNext" value="${esc(obj.next||'')}"></div><div class="field"><label>Progress %</label><input id="fProgress" type="number" value="${obj.progress||0}"></div></div>${actions()}`;
if(type==='admin')b=`<div class="form-grid"><div class="field full"><label>Item</label><input id="fTitle"></div><div class="field"><label>Type</label><input id="fType"></div><div class="field"><label>Status</label><input id="fStatus" value="Open"></div><div class="field"><label>Due/check</label><input id="fDue" type="date"></div></div>${actions()}`;$('#modalBody').innerHTML=b;m.classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function saveModal(){const m=$('#modal'),type=m.dataset.type,id=m.dataset.id;if(type==='task'||type==='backlog'){const o={id:id||uid(),title:$('#fTitle').value.trim(),lane:$('#fLane').value,category:$('#fCategory').value.trim()||'Personal',base:+$('#fBase').value,pita:$('#fPita').value==='true',done:false};if(!o.title)return;if(type==='task'){const old=state.today.find(x=>x.id===id);o.done=old?.done||false;state.today=id?state.today.map(x=>x.id===id?o:x):[...state.today,o]}else state.backlog.push({...o,notes:''})}if(type==='inbox'){const title=$('#fTitle').value.trim();if(!title)return;state.inbox.unshift({id:uid(),title,area:$('#fArea').value.trim(),notes:$('#fNotes').value.trim()})}if(type==='project'){const o={id:id||uid(),title:$('#fTitle').value.trim(),area:$('#fArea').value.trim(),status:$('#fStatus').value,next:$('#fNext').value.trim(),priority:$('#fPriority').value,progress:Math.max(0,Math.min(100,+$('#fProgress').value||0)),notes:''};if(!o.title)return;state.projects=id?state.projects.map(x=>x.id===id?o:x):[o,...state.projects]}if(type==='admin'){const title=$('#fTitle').value.trim();if(!title)return;state.admin.unshift({id:uid(),done:false,title,type:$('#fType').value.trim(),status:$('#fStatus').value.trim(),due:$('#fDue').value})}closeModal();save()}
function closeDay(){const date=iso(),points=pts(),goal=+state.settings.goal||20;const h=state.history.find(x=>x.date===date);if(h)Object.assign(h,{points,goal,hit:points>=goal});else state.history.push({date,points,goal,hit:points>=goal});state.today.forEach(t=>{t.done=false;t.pita=false});state.routines.forEach(r=>r.done=false);save();toast(points+' points logged. Fresh day ready.')}
document.addEventListener('click',e=>{const t=e.target;if(t.matches('[data-nav]'))nav(t.dataset.nav);if(t.id==='fab')modal('task');if(t.matches('[data-add]'))modal(t.dataset.add);if(t.matches('[data-close-modal]')||t.id==='modal')closeModal();if(t.id==='saveModal')saveModal();if(t.id==='closeDayBtn'&&confirm(`Log ${pts()} points and reset today's checkboxes?`))closeDay();if(t.matches('[data-pita]')){const x=state.today.find(i=>i.id===t.dataset.pita);if(x){x.pita=!x.pita;save()}}if(t.matches('[data-edit-task]'))modal('task',state.today.find(i=>i.id===t.dataset.editTask)||{});if(t.matches('[data-backlog-task]')){const x=state.today.find(i=>i.id===t.dataset.backlogTask);if(x){state.backlog.push({...x,done:false,notes:''});state.today=state.today.filter(i=>i.id!==x.id);save()}}if(t.matches('[data-promote]')){const x=state.backlog.find(i=>i.id===t.dataset.promote);if(x){state.today.push({...x,done:false});state.backlog=state.backlog.filter(i=>i.id!==x.id);save()}}if(t.matches('[data-delete-backlog]')){state.backlog=state.backlog.filter(i=>i.id!==t.dataset.deleteBacklog);save()}if(t.matches('[data-process-inbox]')){const x=state.inbox.find(i=>i.id===t.dataset.processInbox);if(x){state.backlog.push({id:x.id,title:x.title,lane:'Bonus',category:x.area||'Personal',base:3,pita:false,notes:x.notes||''});state.inbox=state.inbox.filter(i=>i.id!==x.id);save()}}if(t.matches('[data-project-today]')){const p=state.projects.find(i=>i.id===t.dataset.projectToday);if(p){state.today.push({id:uid(),title:p.next,lane:'Bonus',category:p.area,base:5,pita:false,done:false});save()}}if(t.matches('[data-edit-project]'))modal('project',state.projects.find(i=>i.id===t.dataset.editProject)||{});if(t.matches('[data-routine-today]')){const r=state.routines.find(i=>i.id===t.dataset.routineToday);if(r){state.today.push({id:uid(),title:r.title,lane:'Bonus',category:r.area,base:r.base,pita:false,done:false});save()}}if(t.matches('[data-more]')){more=t.dataset.more;renderMore()}if(t.matches('[data-claim]')){const c=+t.dataset.claim;if(bank()>=c&&confirm(`Spend ${c} points on “${t.dataset.title}”?`)){state.claims.push({date:iso(),title:t.dataset.title,cost:c});save()}}if(t.id==='quickReward'){nav('more');more='rewards';renderMore()}if(t.id==='goalBtn'){const g=+prompt('Daily point goal:',state.settings.goal);if(g>0){state.settings.goal=g;save()}}if(t.id==='exportBtn'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='nicks-life-dashboard-'+iso()+'.json';a.click()}});
document.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-check-task]')){const x=state.today.find(i=>i.id===t.dataset.checkTask);if(x){x.done=t.checked;save()}}if(t.matches('[data-check-routine]')){const x=state.routines.find(i=>i.id===t.dataset.checkRoutine);if(x){x.done=t.checked;save()}}if(t.matches('[data-check-admin]')){const x=state.admin.find(i=>i.id===t.dataset.checkAdmin);if(x){x.done=t.checked;save()}}if(t.matches('[data-project-progress]')){const x=state.projects.find(i=>i.id===t.dataset.projectProgress);if(x){x.progress=+t.value;save()}}});
$('#projectSearch').addEventListener('input',renderProjects);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
